### ISSUE TITLE
Make execution tracebacks

### ISSUE THREAD

**Issue by iranzo** [openshift/assisted-test-infra#527]
Traceback while running `make` execution
~~~sh
sleep 5;  # wait for service to get an address
python3 ./tools/deploy_assisted_installer_configmap.py --target "minikube" --domain "" \
        --base-dns-domains """" --namespace "assisted-installer" --profile "minikube" \
          --enable-auth "false"  \
        --ocp-versions '{\"4.6\":{\"display_name\":\"4.6.16\",\"release_image\":\"quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64\",\"rhcos_image\":\"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso\",\"rhcos_version\":\"46.82.202012051820-0\",\"support_level\":\"production\"},\"4.7\":{\"display_name\":\"4.7-pre-release\",\"release_image\":\"quay.io/openshift-release-dev/ocp-release:4.7.0-rc.0-x86_64\",\"rhcos_image\":\"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.7.0-fc.4/rhcos-4.7.0-fc.4-x86_64-live.x86_64.iso\",\"rhcos_version\":\"47.83.202101171239-0\",\"support_level\":\"beta\"}}' --public-registries "quay.io" \
        --check-cvo False  
error: unable to load --registry-config: error occurred while trying to unmarshal json
Traceback (most recent call last):
  File "./tools/deploy_assisted_installer_configmap.py", line 124, in <module>
    main()
  File "./tools/deploy_assisted_installer_configmap.py", line 46, in main
    verify_ocp_versions(json.loads(json.loads('"{}"'.format(deploy_options.ocp_versions))))
  File "/home/kni/assisted_installer/assisted-service/tools/handle_ocp_versions.py", line 59, in verify_ocp_versions
    verify_image_version(key, metadata["release_image"])
  File "/home/kni/assisted_installer/assisted-service/tools/handle_ocp_versions.py", line 67, in verify_image_version
    major, minor, *_other_version_components = get_oc_version(release_image).split(".")
  File "/home/kni/assisted_installer/assisted-service/tools/handle_ocp_versions.py", line 86, in get_oc_version
    f"oc adm release info '{release_image}' {registry_config} -o template --template {{{{.metadata.version}}}}")
  File "/home/kni/assisted_installer/assisted-service/tools/utils.py", line 65, in check_output
    return subprocess.check_output(cmd, shell=True).decode("utf-8")
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'oc adm release info 'quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64' --registry-config '/tmp/tmp2dly3jm9' -o template --template {{.metadata.version}}' returned non-zero exit status 1.
make: *** [Makefile:191: deploy-service-requirements] Error 1
make: Leaving directory '/home/kni/assisted_installer/assisted-service'
make: *** [Makefile:327: deploy_assisted_service] Error 2
~~~

**Comment by YuviGold** [comment]
It means your `PULL_SECRET` env var is malformed. Can you check that?

/cc @osherdp

**Comment by iranzo** [comment]
Yes, I'm checking the playbook I'm using for it, I would make a PR to get a proper error if it's undefined or the PULL_SECRET_FILE is empty too so that it looks more user-friendly (thanks to Omer for the hint btw)

**Comment by iranzo** [comment]
This line: https://github.com/openshift/assisted-test-infra/blob/master/Makefile#L64 should be checking that at least one of the two is set before doing the 'run' part of the Makefile (as both just fill in the PULL_SECRET var, checking the var is not empty later would be enough or give user a warning

**Comment by YuviGold** [comment]
Should be better handled after https://github.com/openshift/assisted-service/pull/1103

**Comment by iranzo** [comment]
Let's close this
